spring:
  datasource:
    url: jdbc:mysql://localhost:3307/palette
    username: ${USERNAME}
    password: ${PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.MySQL8Dialect

  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false

  datasource.hikari:
    maximum-pool-size: 10
    minimum-idle: 2
    idle-timeout: 10000
    max-lifetime: 1800000
    connection-timeout: 30000
  data:
    redis:
      host: localhost
      port: 6379

jwt:
  secret:
    key: ${JWT_SECRET_KEY}
  access:
    token:
      expiration: ${ACCESS_TOKEN_EXPIRATION}
  refresh:
    token:
      expiration: ${REFRESH_TOKEN_EXPIRATION}

custom:
  manage-key: ${MANAGER_KEY}
